/**
 * Voice manifest — maps keys to audio file paths + fallback text.
 * Audio generated by ElevenLabs (primary) or macOS `say` (fallback).
 * Fallback text used by Web Speech API when no audio clip is loaded.
 */

const BASE = "/audio/voices/";

export interface VoiceEntry {
  file: string;
  text: string;
}

function entry(filename: string, text: string): VoiceEntry {
  return { file: BASE + filename, text };
}

export const voiceManifest: Record<string, VoiceEntry> = {
  // ── Greetings ──
  "hello-kaia": entry(
    "hello-kaia.m4a",
    "Hiii Kaia! Welcome to your world! Are you ready to play?",
  ),
  "hi-kaia": entry("hi-kaia.m4a", "Hey there Kaia! I'm so happy to see you!"),
  "welcome-back": entry(
    "welcome-back.m4a",
    "Yaaay, Kaia's back! I missed you! Let's have fun!",
  ),
  "lets-play": entry(
    "lets-play.m4a",
    "Okay Kaia, let's go! Touch anything you want!",
  ),

  // ── Peekaboo ──
  "peek-hiding-1": entry(
    "peek-hiding-1.m4a",
    "Where did I gooo? Can you find me Kaia?",
  ),
  "peek-hiding-2": entry(
    "peek-hiding-2.m4a",
    "Uh oh! I'm hiiiiding! Where am I?",
  ),
  "peek-hiding-3": entry(
    "peek-hiding-3.m4a",
    "Shhh, I'm hiding! Don't tell anyone!",
  ),
  "peek-reveal-1": entry(
    "peek-reveal-1.m4a",
    "PEEK A BOO! Hahaha, there you are Kaia!",
  ),
  "peek-reveal-2": entry(
    "peek-reveal-2.m4a",
    "BOO! Hehe, I see you! Did I surprise you?",
  ),
  "peek-reveal-3": entry(
    "peek-reveal-3.m4a",
    "Here I am! Ta daaa! Were you looking for me?",
  ),
  "peek-reveal-4": entry(
    "peek-reveal-4.m4a",
    "SURPRISE! Hahaha, I was here the whole time!",
  ),

  // ── Dance ──
  "dance-start-1": entry(
    "dance-start-1.m4a",
    "Ooh ooh ooh! Dance party Kaia! Shake shake shake!",
  ),
  "dance-start-2": entry(
    "dance-start-2.m4a",
    "Let's dance together Kaia! Move your body, wiggle wiggle!",
  ),
  "dance-start-3": entry(
    "dance-start-3.m4a",
    "Dance time! Can you dance with me? Shake your hands!",
  ),
  "dance-whee": entry(
    "dance-whee.m4a",
    "Wheeeee! You're such a good dancer Kaia!",
  ),
  "dance-end": entry(
    "dance-end.m4a",
    "Wooo! That was so much fun! Great dancing!",
  ),

  // ── Jump ──
  "jump-start-1": entry(
    "jump-start-1.m4a",
    "Ready? Set? JUMP! Up up up you go!",
  ),
  "jump-start-2": entry(
    "jump-start-2.m4a",
    "Let's jump sooo high! One, two, three, JUMP!",
  ),
  "jump-start-3": entry(
    "jump-start-3.m4a",
    "Boing boing boing! Can you jump like a bunny Kaia?",
  ),
  "jump-whee": entry("jump-whee.m4a", "Wheeeee! So high! You're flying Kaia!"),
  "jump-land": entry("jump-land.m4a", "And down we go! Boom! Hahaha!"),

  // ── Spin ──
  "spin-start-1": entry(
    "spin-start-1.m4a",
    "Round and round and round we go! Wheee!",
  ),
  "spin-start-2": entry(
    "spin-start-2.m4a",
    "Spin spin spin! Like a little ballerina!",
  ),
  "spin-dizzy": entry(
    "spin-dizzy.m4a",
    "Ohhh, I'm getting dizzy! Hahaha, so silly!",
  ),
  "spin-end": entry(
    "spin-end.m4a",
    "Wooo, that was fast! My head is spinning!",
  ),

  // ── Party ──
  "party-start-1": entry(
    "party-start-1.m4a",
    "YAYYY! Party time Kaia! Let's celebrate!",
  ),
  "party-start-2": entry(
    "party-start-2.m4a",
    "Woo hoo! It's a party! Everybody dance!",
  ),
  "party-yay": entry(
    "party-yay.m4a",
    "Yayyy Kaia! You are AMAZING! I love you so much!",
  ),
  "party-confetti": entry(
    "party-confetti.m4a",
    "Confetti! Sparkles! Wooo, so pretty!",
  ),

  // ── Praise & Exclamations ──
  "praise-amazing": entry(
    "praise-amazing.m4a",
    "Oh my goodness, AMAZING Kaia! You did it!",
  ),
  "praise-wonderful": entry(
    "praise-wonderful.m4a",
    "That is SO wonderful! I'm so proud of you!",
  ),
  "praise-superstar": entry(
    "praise-superstar.m4a",
    "You're a superstar Kaia! Give yourself a big hug!",
  ),
  "praise-smart": entry(
    "praise-smart.m4a",
    "Wow, you're so smart! You got it right!",
  ),
  "praise-try-again": entry(
    "praise-try-again.m4a",
    "Hmm, not quite! That's okay, let's try again! You can do it!",
  ),
  "praise-yay-kaia": entry(
    "praise-yay-kaia.m4a",
    "Yaaay Kaia! Clap your hands with me!",
  ),
  "praise-wow": entry("praise-wow.m4a", "Wooow! Look at that! So beautiful!"),
  "praise-good-job": entry(
    "praise-good-job.m4a",
    "Good job Kaia! You're getting so good at this!",
  ),

  // ── Auto-play phrases ──
  "auto-love": entry(
    "auto-love.m4a",
    "Hi Kaia! I love you sooo much! You're my favorite!",
  ),
  "auto-twinkle": entry(
    "auto-twinkle.m4a",
    "Twinkle twinkle little star, how I wonder what you are!",
  ),
  "auto-animals": entry(
    "auto-animals.m4a",
    "Old MacDonald had a farm, and on his farm he had a COW! Moooo!",
  ),
  "auto-abc": entry("auto-abc.m4a", "A B C D E F G, H I J K L M N O P!"),
  "auto-head-shoulders": entry(
    "auto-head-shoulders.m4a",
    "Head, shoulders, knees and toes, knees and toes!",
  ),
  "auto-superstar": entry(
    "auto-superstar.m4a",
    "Kaia is a superstar! The most amazing girl in the whole world!",
  ),
  "auto-counting": entry(
    "auto-counting.m4a",
    "Let's count together! One, two, three, four, five!",
  ),
  "auto-row": entry(
    "auto-row.m4a",
    "Row row row your boat, gently down the stream!",
  ),
  "auto-baa": entry("auto-baa.m4a", "Baa baa black sheep, have you any wool?"),
  "auto-itsy": entry(
    "auto-itsy.m4a",
    "The itsy bitsy spider climbed up the water spout!",
  ),

  // ── Colors ──
  "color-intro": entry(
    "color-intro.m4a",
    "Ooh, let's play with colors! Colors are everywhere!",
  ),
  "tap-the-red": entry(
    "tap-the-red.m4a",
    "Can you find the RED one? Red is like a fire truck! Nee-naw nee-naw!",
  ),
  "tap-the-blue": entry(
    "tap-the-blue.m4a",
    "Where is the BLUE one? Blue like the sky! Look up, the sky is blue!",
  ),
  "tap-the-green": entry(
    "tap-the-green.m4a",
    "Find the GREEN one! Green like the grass and the trees!",
  ),
  "tap-the-yellow": entry(
    "tap-the-yellow.m4a",
    "Can you tap the YELLOW one? Yellow like the sun! So bright!",
  ),
  "tap-the-purple": entry(
    "tap-the-purple.m4a",
    "Where's the PURPLE one? Purple like a grape! Yummy!",
  ),
  "tap-the-orange": entry(
    "tap-the-orange.m4a",
    "Find the ORANGE one! Orange like an orange! And a pumpkin!",
  ),
  "tap-the-pink": entry(
    "tap-the-pink.m4a",
    "Tap the PINK one! Pink like a flamingo! Pretty pretty pink!",
  ),
  "tap-the-white": entry(
    "tap-the-white.m4a",
    "Where is the WHITE one? White like fluffy clouds! And snow!",
  ),
  "tap-the-black": entry(
    "tap-the-black.m4a",
    "Can you find the BLACK one? Black like nighttime! Shh, everyone's sleeping!",
  ),
  "tap-the-brown": entry(
    "tap-the-brown.m4a",
    "Find the BROWN one! Brown like chocolate! Mmm, yummy!",
  ),
  "yes-red": entry(
    "yes-red.m4a",
    "YES! That's RED! Great job Kaia! Red like a fire truck, nee-naw!",
  ),
  "yes-blue": entry(
    "yes-blue.m4a",
    "YES! That's BLUE! So smart Kaia! Blue like the beautiful sky!",
  ),
  "yes-green": entry(
    "yes-green.m4a",
    "YES! That's GREEN! Amazing! Green like the trees, whoosh whoosh!",
  ),
  "yes-yellow": entry(
    "yes-yellow.m4a",
    "YES! YELLOW! You found it! Bright like the sunshine!",
  ),
  "yes-purple": entry(
    "yes-purple.m4a",
    "YES! PURPLE! Wonderful Kaia! Purple like yummy grapes!",
  ),
  "yes-orange": entry(
    "yes-orange.m4a",
    "YES! ORANGE! You got it! Orange like a big round orange!",
  ),
  "yes-pink": entry(
    "yes-pink.m4a",
    "YES! PINK! Beautiful! Pretty pretty pink!",
  ),
  "yes-white": entry(
    "yes-white.m4a",
    "YES! WHITE! So smart! White like soft fluffy clouds!",
  ),
  "yes-black": entry(
    "yes-black.m4a",
    "YES! BLACK! Great job! Black like the nighttime sky with stars!",
  ),
  "yes-brown": entry(
    "yes-brown.m4a",
    "YES! BROWN! You found it! Brown like chocolate, mmm!",
  ),
  "wrong-color": entry(
    "wrong-color.m4a",
    "Hmm, not quite! That's okay, let's try again! You can do it!",
  ),

  // ── Animals ──
  "animal-intro": entry(
    "animal-intro.m4a",
    "Let's meet some animal friends! What sound do they make?",
  ),
  "animal-cow": entry(
    "animal-cow.m4a",
    "Look, it's a COW! The cow says MOOOO! Can you say moo Kaia? Mooooo!",
  ),
  "animal-dog": entry(
    "animal-dog.m4a",
    "It's a DOGGY! Woof woof woof! Can you bark like a doggy? Woof woof!",
  ),
  "animal-cat": entry(
    "animal-cat.m4a",
    "Aww, a KITTY CAT! Meow meow! So cute! Can you say meow?",
  ),
  "animal-duck": entry(
    "animal-duck.m4a",
    "Look, a DUCK! Quack quack quack! Ducks go quack quack in the water!",
  ),
  "animal-pig": entry(
    "animal-pig.m4a",
    "A little PIGGY! Oink oink oink! Piggies love to play in the mud! Splash!",
  ),
  "animal-sheep": entry(
    "animal-sheep.m4a",
    "It's a SHEEP! Baaaa baaaa! Sheep are so fluffy and soft!",
  ),
  "animal-lion": entry(
    "animal-lion.m4a",
    "ROARRR! It's a LION! The king of the jungle! Roarrr! Can you roar Kaia?",
  ),
  "animal-frog": entry(
    "animal-frog.m4a",
    "Ribbit ribbit! It's a FROG! Frogs go hop hop hop! Jump like a frog!",
  ),
  "animal-horse": entry(
    "animal-horse.m4a",
    "Look, a HORSE! Neigh neigh! Horses go clip clop clip clop!",
  ),
  "animal-chicken": entry(
    "animal-chicken.m4a",
    "It's a CHICKEN! Bawk bawk bawk ba-GAWK! Chickens are so funny!",
  ),
  "animal-owl": entry(
    "animal-owl.m4a",
    "Whooo! It's an OWL! The owl says hoo hoo! Owls come out at nighttime!",
  ),
  "animal-elephant": entry(
    "animal-elephant.m4a",
    "It's a big ELEPHANT! BRRRRR! Elephants are sooo big and they squirt water! Splash!",
  ),

  // ── Counting ──
  "count-intro": entry(
    "count-intro.m4a",
    "Let's count together Kaia! Every time you tap, we count one more! Ready?",
  ),
  "count-1": entry("count-1.m4a", "ONE! Woo, one tap! Keep going Kaia!"),
  "count-2": entry("count-2.m4a", "TWO! That's two! You're doing great!"),
  "count-3": entry("count-3.m4a", "THREE! Three taps! Wow, so many!"),
  "count-4": entry("count-4.m4a", "FOUR! Four already! You're so fast!"),
  "count-5": entry("count-5.m4a", "FIVE! Halfway there! High five!"),
  "count-6": entry("count-6.m4a", "SIX! Six taps! Almost there Kaia!"),
  "count-7": entry("count-7.m4a", "SEVEN! Seven! Keep going, you can do it!"),
  "count-8": entry("count-8.m4a", "EIGHT! Eight taps! So close!"),
  "count-9": entry("count-9.m4a", "NINE! Nine! One more Kaia, one more!"),
  "count-10": entry(
    "count-10.m4a",
    "TEN! YAAAY! You counted all the way to TEN! I'm so proud of you Kaia!",
  ),

  // ── Shapes ──
  "shape-intro": entry(
    "shape-intro.m4a",
    "Let's learn about shapes! Shapes are all around us!",
  ),
  "tap-the-circle": entry(
    "tap-the-circle.m4a",
    "Can you find the CIRCLE? Circles are round, like a ball! Round and round!",
  ),
  "tap-the-square": entry(
    "tap-the-square.m4a",
    "Where's the SQUARE? Squares have four sides, all the same! Like a window!",
  ),
  "tap-the-triangle": entry(
    "tap-the-triangle.m4a",
    "Find the TRIANGLE! Triangles have three pointy corners! Like a mountain!",
  ),
  "tap-the-star": entry(
    "tap-the-star.m4a",
    "Where's the STAR? Stars twinkle in the sky at night! Twinkle twinkle!",
  ),
  "tap-the-heart": entry(
    "tap-the-heart.m4a",
    "Can you find the HEART? Hearts mean love! I love you Kaia!",
  ),
  "tap-the-diamond": entry(
    "tap-the-diamond.m4a",
    "Find the DIAMOND! Diamonds are so sparkly and beautiful!",
  ),
  "yes-circle": entry(
    "yes-circle.m4a",
    "YES! That's a CIRCLE! Round like a ball! Great job Kaia!",
  ),
  "yes-square": entry(
    "yes-square.m4a",
    "YES! A SQUARE! Four sides! So smart Kaia!",
  ),
  "yes-triangle": entry(
    "yes-triangle.m4a",
    "YES! A TRIANGLE! Three pointy corners! Amazing!",
  ),
  "yes-star": entry("yes-star.m4a", "YES! A STAR! Twinkle twinkle! Wonderful!"),
  "yes-heart": entry(
    "yes-heart.m4a",
    "YES! A HEART! Full of love! I love you!",
  ),
  "yes-diamond": entry(
    "yes-diamond.m4a",
    "YES! A DIAMOND! Sparkly! Beautiful job!",
  ),

  // ── Body parts ──
  "body-intro": entry(
    "body-intro.m4a",
    "Let's find our body parts! Touch your body when you hear it!",
  ),
  "body-head": entry(
    "body-head.m4a",
    "Where's your HEAD? Can you touch your head? Touch the top of your head!",
  ),
  "body-eyes": entry(
    "body-eyes.m4a",
    "Where are your EYES? Blink blink! Can you blink your eyes Kaia?",
  ),
  "body-nose": entry(
    "body-nose.m4a",
    "Where's your NOSE? Boop! Can you touch your nose? Boop!",
  ),
  "body-mouth": entry(
    "body-mouth.m4a",
    "Where's your MOUTH? Open wide! Ahhh! Can you say ahhh?",
  ),
  "body-ears": entry(
    "body-ears.m4a",
    "Where are your EARS? Can you wiggle your ears? I can hear you!",
  ),
  "body-hands": entry(
    "body-hands.m4a",
    "Show me your HANDS! Wave your hands! Wave wave wave!",
  ),
  "body-feet": entry(
    "body-feet.m4a",
    "Where are your FEET? Stomp stomp stomp! Stamp your feet!",
  ),
  "body-tummy": entry(
    "body-tummy.m4a",
    "Where's your TUMMY? Can you pat your tummy? Pat pat pat!",
  ),

  // ── Music ──
  "music-start": entry(
    "music-start.m4a",
    "Music time! Let's dance and sing together Kaia!",
  ),
  "dj-bunny": entry(
    "dj-bunny.m4a",
    "YO! DJ Bunny in the HOUSE! Let's get this party STARTED! Boom boom!",
  ),
  "music-stop": entry(
    "music-stop.m4a",
    "Music's taking a little break! But we can start it again anytime!",
  ),
};

/** Helper to get just the file path for a key */
export function getVoicePath(key: string): string | undefined {
  return voiceManifest[key]?.file;
}

/** Helper to get fallback text for a key */
export function getVoiceText(key: string): string {
  return voiceManifest[key]?.text || key;
}

/** All voice keys for preloading */
export const allVoiceKeys = Object.keys(voiceManifest);

/** Priority clips to load first (splash + common praise) */
export const priorityKeys = [
  "hello-kaia",
  "praise-amazing",
  "praise-yay-kaia",
  "praise-try-again",
  "peek-reveal-1",
  "dance-start-1",
  "jump-start-1",
  "party-start-1",
  "music-start",
  "count-intro",
];
