/**
 * Maps voice clip keys to their MP3 file paths.
 * Paths are relative to /audio/voices/ in the public directory.
 * Generated by scripts/generate-voices.sh using macOS `say` command.
 */

const BASE = "/audio/voices/";

function v(file: string): string {
  return BASE + file;
}

export const voiceManifest: Record<string, string> = {
  // Greetings
  "hello-kaia": v("hello-kaia.m4a"),
  "hi-kaia": v("hi-kaia.m4a"),
  welcome: v("welcome.m4a"),
  "hi-there": v("hi-there.m4a"),
  "i-love-you": v("i-love-you.m4a"),

  // Peekaboo
  "peek-a-boo": v("peek-a-boo.m4a"),
  "where-am-i": v("where-am-i.m4a"),
  "im-hiding": v("im-hiding.m4a"),
  "here-i-am": v("here-i-am.m4a"),
  boo: v("boo.m4a"),
  surprise: v("surprise.m4a"),
  "i-see-you-kaia": v("i-see-you-kaia.m4a"),

  // Dance
  "dance-dance-dance": v("dance-dance-dance.m4a"),
  "shake-shake-shake": v("shake-shake-shake.m4a"),
  "lets-dance-kaia": v("lets-dance-kaia.m4a"),
  "wiggle-wiggle": v("wiggle-wiggle.m4a"),

  // Jump
  "jump-jump-jump": v("jump-jump-jump.m4a"),
  "boing-boing": v("boing-boing.m4a"),
  "up-up-up": v("up-up-up.m4a"),
  "wheee-so-high": v("wheee-so-high.m4a"),

  // Spin
  "round-and-round": v("round-and-round.m4a"),
  "spin-spin-spin": v("spin-spin-spin.m4a"),
  dizzy: v("dizzy.m4a"),
  "wheee-spinning": v("wheee-spinning.m4a"),

  // Party
  "yay-party-time": v("yay-party-time.m4a"),
  hooray: v("hooray.m4a"),
  "we-did-it": v("we-did-it.m4a"),
  amazing: v("amazing.m4a"),

  // Exclamations
  wheee: v("wheee.m4a"),
  yay: v("yay.m4a"),
  superstar: v("superstar.m4a"),
  wonderful: v("wonderful.m4a"),
  "yay-kaia": v("yay-kaia.m4a"),
  "great-job-kaia": v("great-job-kaia.m4a"),
  "you-did-it": v("you-did-it.m4a"),
  "kaia-is-a-superstar": v("kaia-is-a-superstar.m4a"),

  // Auto-play phrases
  "hi-kaia-i-love-you": v("hi-kaia-i-love-you.m4a"),
  "twinkle-twinkle": v("twinkle-twinkle.m4a"),
  "animal-sounds-mixed": v("animal-sounds-mixed.m4a"),
  abcdefg: v("abcdefg.m4a"),
  "head-shoulders": v("head-shoulders.m4a"),
  "old-macdonald": v("old-macdonald.m4a"),
  "one-two-three-four-five": v("one-two-three-four-five.m4a"),
  "row-row-row": v("row-row-row.m4a"),
  "baa-baa-black-sheep": v("baa-baa-black-sheep.m4a"),

  // Colors
  "tap-the-red": v("tap-the-red.m4a"),
  "tap-the-blue": v("tap-the-blue.m4a"),
  "tap-the-green": v("tap-the-green.m4a"),
  "tap-the-yellow": v("tap-the-yellow.m4a"),
  "tap-the-purple": v("tap-the-purple.m4a"),
  "tap-the-orange": v("tap-the-orange.m4a"),
  "tap-the-pink": v("tap-the-pink.m4a"),
  "tap-the-white": v("tap-the-white.m4a"),
  "tap-the-black": v("tap-the-black.m4a"),
  "tap-the-brown": v("tap-the-brown.m4a"),
  "yes-thats-red": v("yes-thats-red.m4a"),
  "yes-thats-blue": v("yes-thats-blue.m4a"),
  "yes-thats-green": v("yes-thats-green.m4a"),
  "yes-thats-yellow": v("yes-thats-yellow.m4a"),
  "yes-thats-purple": v("yes-thats-purple.m4a"),
  "yes-thats-orange": v("yes-thats-orange.m4a"),
  "yes-thats-pink": v("yes-thats-pink.m4a"),
  "yes-thats-white": v("yes-thats-white.m4a"),
  "yes-thats-black": v("yes-thats-black.m4a"),
  "yes-thats-brown": v("yes-thats-brown.m4a"),

  // Animals
  "animal-cow": v("animal-cow.m4a"),
  "animal-dog": v("animal-dog.m4a"),
  "animal-cat": v("animal-cat.m4a"),
  "animal-duck": v("animal-duck.m4a"),
  "animal-pig": v("animal-pig.m4a"),
  "animal-sheep": v("animal-sheep.m4a"),
  "animal-lion": v("animal-lion.m4a"),
  "animal-frog": v("animal-frog.m4a"),
  "animal-horse": v("animal-horse.m4a"),
  "animal-chicken": v("animal-chicken.m4a"),
  "animal-owl": v("animal-owl.m4a"),
  "animal-elephant": v("animal-elephant.m4a"),

  // Counting
  "lets-count": v("lets-count.m4a"),
  "count-1": v("count-1.m4a"),
  "count-2": v("count-2.m4a"),
  "count-3": v("count-3.m4a"),
  "count-4": v("count-4.m4a"),
  "count-5": v("count-5.m4a"),
  "count-6": v("count-6.m4a"),
  "count-7": v("count-7.m4a"),
  "count-8": v("count-8.m4a"),
  "count-9": v("count-9.m4a"),
  "count-10": v("count-10.m4a"),
  "yay-counted-to-ten": v("yay-counted-to-ten.m4a"),

  // Shapes
  "tap-the-circle": v("tap-the-circle.m4a"),
  "tap-the-square": v("tap-the-square.m4a"),
  "tap-the-triangle": v("tap-the-triangle.m4a"),
  "tap-the-star": v("tap-the-star.m4a"),
  "tap-the-heart": v("tap-the-heart.m4a"),
  "tap-the-diamond": v("tap-the-diamond.m4a"),
  "yes-thats-a-circle": v("yes-thats-a-circle.m4a"),
  "yes-thats-a-square": v("yes-thats-a-square.m4a"),
  "yes-thats-a-triangle": v("yes-thats-a-triangle.m4a"),
  "yes-thats-a-star": v("yes-thats-a-star.m4a"),
  "yes-thats-a-heart": v("yes-thats-a-heart.m4a"),
  "yes-thats-a-diamond": v("yes-thats-a-diamond.m4a"),

  // Body parts
  "body-head": v("body-head.m4a"),
  "body-eyes": v("body-eyes.m4a"),
  "body-nose": v("body-nose.m4a"),
  "body-mouth": v("body-mouth.m4a"),
  "body-ears": v("body-ears.m4a"),
  "body-hands": v("body-hands.m4a"),
  "body-feet": v("body-feet.m4a"),
  "body-tummy": v("body-tummy.m4a"),

  // Music
  "music-time": v("music-time.m4a"),
  "dj-bunny-in-the-house": v("dj-bunny-in-the-house.m4a"),
};

/** All voice keys for preloading */
export const allVoiceKeys = Object.keys(voiceManifest);

/** Priority clips to load first (splash + common) */
export const priorityKeys = [
  "hello-kaia",
  "yay-kaia",
  "amazing",
  "wheee",
  "yay",
  "peek-a-boo",
  "here-i-am",
  "dance-dance-dance",
  "jump-jump-jump",
  "music-time",
];
